#! /usr/local/bin/gmake
# makfile for yaep5

vpath %.h  ..
vpath %.cpp ..

include ../Makefile
CPPFLAGS= -ftemplate-depth-25 -pg -O2 -Wall -Wno-sign-compare -I/cs/duff2/ninio/LibB/Include/
LDFLAGS+= -pg




