/* bootstrap_prog_cmdline.h */

/* File autogenerated by gengetopt version 2.13  */

#ifndef BOOTSTRAP_PROG_CMDLINE_H
#define BOOTSTRAP_PROG_CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef BOOTSTRAP_PROG_CMDLINE_PARSER_PACKAGE
#define BOOTSTRAP_PROG_CMDLINE_PARSER_PACKAGE "bootstrap"
#endif

#ifndef BOOTSTRAP_PROG_CMDLINE_PARSER_VERSION
#define BOOTSTRAP_PROG_CMDLINE_PARSER_VERSION "1.0.a1"
#endif

struct bootstrap_prog_args_info
{
  char * treesList_arg;	/* filename of list of input trees.  */
  char * reftree_arg;	/* Refremce Tree file name.  */
  char * outputfile_arg;	/* Output tree file (default='-').  */
  char * Logfile_arg;	/* Log file output name (default='-').  */
  int verbose_arg;	/* Log report level (verbose) (default='0').  */
  float ConsensusLevel_arg;	/* use only branches with sport above this (default='0.5').  */
  int noBranchLen_flag;	/* Do not output branch lengths in output tree (default=off).  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int treesList_given ;	/* Whether treesList was given.  */
  int reftree_given ;	/* Whether reftree was given.  */
  int outputfile_given ;	/* Whether outputfile was given.  */
  int Logfile_given ;	/* Whether Logfile was given.  */
  int verbose_given ;	/* Whether verbose was given.  */
  int ConsensusLevel_given ;	/* Whether ConsensusLevel was given.  */
  int noBranchLen_given ;	/* Whether noBranchLen was given.  */

} ;

int bootstrap_prog_cmdline_parser (int argc, char * const *argv, struct bootstrap_prog_args_info *args_info);
int bootstrap_prog_cmdline_parser2 (int argc, char * const *argv, struct bootstrap_prog_args_info *args_info, int override, int initialize, int check_required);

void bootstrap_prog_cmdline_parser_print_help(void);
void bootstrap_prog_cmdline_parser_print_version(void);

void bootstrap_prog_cmdline_parser_init (struct bootstrap_prog_args_info *args_info);
void bootstrap_prog_cmdline_parser_free (struct bootstrap_prog_args_info *args_info);

int bootstrap_prog_cmdline_parser_required (struct bootstrap_prog_args_info *args_info, const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* BOOTSTRAP_PROG_CMDLINE_H */
