"""Folders.py: folder variables"""

RAW = "results/transcriptome/"
BUSCO = "results/busco/"
TRANSDECODER = "results/transdecoder/"
CDHIT = "results/cdhit/"

ORTHOFINDER = "results/orthofinder/"
OF_PREPARE = ORTHOFINDER + "OrthoFinder/Results_prepare/"
OF_GROUPS = ORTHOFINDER + "OrthoFinder/Results_groups/"
OF_SEQUENCES = OF_GROUPS + "Orthogroup_Sequences/"
OF_TREES = ORTHOFINDER + "OrthoFinder/Results_trees/"
OF_MSA = OF_TREES + "MultipleSequenceAlignments/"
OF_GENE_TREES = OF_TREES + "Gene_Trees/"
OF_ORTHOLOGUES = ORTHOFINDER + "OrthoFinder/Results_orthologues/"
OF_RESOLVED_GENE_TREES = OF_ORTHOLOGUES + "Resolved_Gene_Trees/"

HOMOLOGS = "results/homologs/"
HOMOLOGS_R1 = HOMOLOGS + "round1/"
HOMOLOGS_R2 = HOMOLOGS + "round2/"
HOMOLOGS_RT = HOMOLOGS + "root_to_tip/"
HOMOLOGS_REFINE1 = HOMOLOGS + "refine1/"
HOMOLOGS_REFINE2 = HOMOLOGS + "refine2/"

TREE = "results/tree/"
TREE_ALN = TREE + "alignments/"
