#! /usr/local/bin/gmake
#  $Id: Makefile 961 2006-11-06 17:38:36Z privmane $

# In order to compile with doubleRep run make like this:  make doubleRep

Libsources= isEqualTree.cpp
#Libsources=
LIBNAME = isEqualTree

# LibCsources= cmdline.c
# LibCsources += getopt.c getopt1.c

EXEC = isEqualTree

include ../Makefile.generic
