#! /bin/tcsh -f

echo "test constraints - with tree as both constraint tree and input tree"
./constraints_test lys.tree lys.tree
echo "test constraints - with different, matching trees"
./constraints_test lys.tree lys.tree.consraint2
echo "test constraints - with different, non matching trees"
./constraints_test lys.tree lys.tree.consraint3

