#! /bin/tcsh -f



foreach ct (lys_test*.ctree)
    echo $ct
    cat $ct
    echo ""
    echo 'Running "../semphy -H -s lys6.seq  -t lys6.tree --jtt -c '$ct' -v5 -L"'
    echo ""
    ../semphy -H -s lys6.seq  -t lys6.tree --jtt -c $ct -v5 -L
    echo ""
    echo ""
end
