#! /bin/tcsh -f


echo "SEMPHY with Constraints from given tree"

foreach ct (lys_test*.ctree)
    echo $ct
    cat $ct
    echo ""
    echo 'Running "../semphy -H -s lys6.seq  -t lys6.tree --jtt -c '$ct' -v5 -S"'
    echo ""
    ../semphy -H -s lys6.seq  -t lys6.tree --jtt -c $ct -v5 -S
    echo ""
    echo ""
end
